services:
  - type: web
    name: rccg-backend
    env: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app ./cmd/server
    startCommand: ./app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rccg-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GIN_MODE
        value: release